# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!


target 'WAStickersThirdParty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SDWebImage'
    pod 'FontAwesome.swift'
    pod 'Toast-Swift'
    pod 'Kingfisher'
    pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift4.2' # Swift 4.2
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
    pod 'YPImagePicker'
   
end

target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
